name: CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [admin-ui, admin-api, user-ui, user-api] # List of subdirectories and repositories

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Directory Permissions
        run: chmod -R 755 ./

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push to ECR
        env:
          ECR_REGISTRY: 824813378441.dkr.ecr.us-east-1.amazonaws.com
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          cd ${{ matrix.app }}
          docker build -t $ECR_REGISTRY/${{ matrix.app }}:${{ github.run_number }} .
          docker push $ECR_REGISTRY/${{ matrix.app }}:${{ github.run_number }}
